ServerTokens Prod
ServerSignature Off
TraceEnable Off

PassEnv CTF_FLAG USER_SEED USER_ID STUDENT_ID FLAG_SEED

<Directory /var/www/html>
    Options -Indexes
    AllowOverride None
</Directory>

<FilesMatch "^\.">
    Require all denied
</FilesMatch>
